[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "globe3d"
version = "0.1.0"
description = "A Python library for creating 3D models of globes with surfaces perturbed by geographic displacement grids."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "matplotlib",
    "scipy",
    "tqdm",
    "netCDF4",
    "rasterio",
    "trimesh",
    "cmocean",
]

[project.urls]
"Homepage" = "https://github.com/jeffwinterbourne/3D_globes"
"Bug Tracker" = "https://github.com/jeffwinterbourne/3D_globes/issues"

[tool.setuptools.packages.find]
where = ["src"]
