import os
import numpy as np
import pytest
from globe3d.io import write_stl_binary, fix_face_chirality, write_obj_with_vertex_colors

def test_fix_face_chirality():
    # Sphere center at 0, 0, 0
    # Face pointing outward: (0,0,1) -> (1,0,1) -> (0,1,1)
    # Centroid: (1/3, 1/3, 1)
    # Normal: np.cross((1,0,0), (0,1,0)) = (0,0,1)
    # Dot product: (0,0,1) . (1/3, 1/3, 1) = 1 > 0 (Correct, should not flip)
    
    # Face pointing inward: (0,0,1) -> (0,1,1) -> (1,0,1)
    # Normal: np.cross((0,1,0), (1,0,0)) = (0,0,-1)
    # Dot product: (0,0,-1) . (1/3, 1/3, 1) = -1 < 0 (Incorrect, should flip)

    vertices = np.array([
        [0.0, 0.0, 1.0],
        [1.0, 0.0, 1.0],
        [0.0, 1.0, 1.0]
    ])

    faces = np.array([
        [0, 1, 2],  # Outward face
        [0, 2, 1]   # Inward face
    ])

    corrected = fix_face_chirality(vertices, faces, center=(0.0, 0.0, 0.0))

    # The outward face should remain [0, 1, 2]
    assert np.array_equal(corrected[0], [0, 1, 2])
    # The inward face [0, 2, 1] should swap indices 1 and 2 to become [0, 1, 2]
    assert np.array_equal(corrected[1], [0, 1, 2])


def test_write_stl_binary(tmp_path):
    filename = tmp_path / "test.stl"
    vertices = np.array([
        [0.0, 0.0, 0.0],
        [1.0, 0.0, 0.0],
        [0.0, 1.0, 0.0]
    ], dtype=np.float32)
    faces = np.array([[0, 1, 2]], dtype=np.int32)

    write_stl_binary(str(filename), vertices, faces)

    assert filename.exists()
    # Binary STL size should be: 80 bytes header + 4 bytes count + 50 bytes per facet = 134 bytes
    assert filename.stat().st_size == 134

    # Verify binary contents
    with open(filename, 'rb') as f:
        header = f.read(80)
        assert header.startswith(b'Generated by globe3d.py')
        count = np.frombuffer(f.read(4), dtype='<u4')[0]
        assert count == 1
        
        # Read the facet: normal (3f), v0 (3f), v1 (3f), v2 (3f), attr (u2)
        normal = np.frombuffer(f.read(12), dtype='<f4')
        v0 = np.frombuffer(f.read(12), dtype='<f4')
        v1 = np.frombuffer(f.read(12), dtype='<f4')
        v2 = np.frombuffer(f.read(12), dtype='<f4')
        attr = np.frombuffer(f.read(2), dtype='<u2')[0]

        assert np.allclose(normal, [0.0, 0.0, 1.0])
        assert np.allclose(v0, [0.0, 0.0, 0.0])
        assert np.allclose(v1, [1.0, 0.0, 0.0])
        assert np.allclose(v2, [0.0, 1.0, 0.0])
        assert attr == 0


def test_write_obj_with_vertex_colors(tmp_path):
    filename = tmp_path / "test.obj"
    vertices = np.array([
        [0.0, 0.0, 0.0],
        [1.0, 0.0, 0.0],
        [0.0, 1.0, 0.0]
    ])
    faces = np.array([[0, 1, 2]])
    colors = np.array([
        [1.0, 0.0, 0.0],
        [0.0, 1.0, 0.0],
        [0.0, 0.0, 1.0]
    ])

    write_obj_with_vertex_colors(str(filename), vertices, faces, colors, fix_normals=False)

    assert filename.exists()
    with open(filename, 'r') as f:
        lines = f.read().splitlines()

    assert lines[0] == "# OBJ file with vertex colors"
    assert lines[1] == "v 0.000000 0.000000 0.000000 1.000000 0.000000 0.000000"
    assert lines[2] == "v 1.000000 0.000000 0.000000 0.000000 1.000000 0.000000"
    assert lines[3] == "v 0.000000 1.000000 0.000000 0.000000 0.000000 1.000000"
    assert lines[4] == "f 1 2 3"
