import numpy as np
import struct

def write_stl_binary(filename, vertices, faces):
    """
    Writes a triangulated mesh (vertices and faces) to a binary STL file.
    
    Parameters:
      filename (str): Output file path.
      vertices: (n_points x 3) array.
      faces: (n_faces x 3) array of indices.
    """
    with open(filename, 'wb') as f:
        # 80-byte header (padded if necessary)
        header = b'Generated by globe3d.py'
        header += b' ' * (80 - len(header))
        f.write(header)
        # Write number of triangles
        f.write(struct.pack('<I', len(faces)))
        for face in faces:
            v1, v2, v3 = vertices[face]
            normal = np.cross(v2 - v1, v3 - v1)
            norm = np.linalg.norm(normal)
            if norm == 0:
                normal = np.array([0.0, 0.0, 0.0])
            else:
                normal = normal / norm
            # Each facet: normal (3 floats), vertices (9 floats), attribute byte count (2 bytes)
            data = struct.pack('<3f', *normal)
            data += struct.pack('<3f', *v1)
            data += struct.pack('<3f', *v2)
            data += struct.pack('<3f', *v3)
            data += struct.pack('<H', 0)
            f.write(data)


def fix_face_chirality(vertices, faces, center=(0.0, 0.0, 0.0)):
    """
    Ensures that each face (triangle) of the mesh has its normal vector pointing outward 
    (away from the given center). For each face the function computes the face normal 
    via the cross product and then compares it with the vector from the center to the face centroid.
    If the face appears to be inverted (dot product < 0), the ordering of the last two vertices is swapped.

    Parameters:
      vertices (numpy.ndarray): Array of shape (n_points, 3) representing vertices.
      faces (numpy.ndarray): Array of shape (n_faces, 3) with indices into vertices.
      center (tuple, list, or numpy.ndarray): The center point of the sphere (defaults to (0,0,0)).

    Returns:
      numpy.ndarray: New array of faces with corrected chirality.
    """
    center = np.array(center, dtype=np.float64)
    corrected_faces = []
    for face in faces:
        v0, v1, v2 = vertices[face[0]], vertices[face[1]], vertices[face[2]]
        # Compute normal using the cross product
        normal = np.cross(v1 - v0, v2 - v0)
        # Compute the centroid of the triangle
        face_center = (v0 + v1 + v2) / 3.0
        # Vector from sphere center to the face center
        vec = face_center - center
        # If the dot product is negative, the face normal is pointing inward so flip the face.
        if np.dot(normal, vec) < 0:
            corrected_faces.append([face[0], face[2], face[1]])
        else:
            corrected_faces.append(face.tolist())
    return np.array(corrected_faces, dtype=np.int32)


def write_obj_with_vertex_colors(filename, vertices, faces, colors,
                                  center=(0.0, 0.0, 0.0), fix_normals=False):
    """
    Writes a mesh with per-vertex colors to an OBJ file using a common
    vertex-color extension.  The vertex lines are written as
    ``v x y z r g b``.

    Parameters:
      filename (str): Output OBJ file path.
      vertices (numpy.ndarray): Array of shape (n_points, 3) with vertex
          coordinates.
      faces (numpy.ndarray): Array of shape (n_faces, 3) with indices into
          vertices.
      colors (numpy.ndarray): Array of shape (n_points, 3) with RGB values
          (in [0, 1]).
      center (tuple): The center of the sphere.  Only used when
          *fix_normals* is True.
      fix_normals (bool): If True, apply ``fix_face_chirality`` to force
          all face normals to point away from *center*.  This is appropriate
          for simple convex meshes (e.g. a solid outer shell) but **must
          be False** for hollow/manifold meshes produced by boolean
          operations, where inner faces legitimately point inward.
          Defaults to False.
    """
    if fix_normals:
        faces_out = fix_face_chirality(vertices, faces, center)
    else:
        faces_out = faces

    with open(filename, 'w') as f:
        f.write("# OBJ file with vertex colors\n")
        for v, c in zip(vertices, colors):
            f.write("v {:.6f} {:.6f} {:.6f} {:.6f} {:.6f} {:.6f}\n".format(
                v[0], v[1], v[2], c[0], c[1], c[2]
            ))
        for face in faces_out:
            # OBJ indices are 1-based.
            f.write("f {} {} {}\n".format(face[0] + 1, face[1] + 1, face[2] + 1))
