import numpy as np
import struct
from .mesh import fix_face_chirality


def write_stl_binary(filename, vertices, faces):
    """Writes a triangulated mesh (vertices and faces) to a binary STL file.

    Uses vectorized NumPy operations for maximum speed.

    Args:
        filename (str): Output file path.
        vertices (numpy.ndarray): Array of shape (n_points, 3) containing vertex coordinates.
        faces (numpy.ndarray): Array of shape (n_faces, 3) containing face indices.
    """
    vertices = np.asarray(vertices, dtype=np.float32)
    faces = np.asarray(faces, dtype=np.int32)
    F = faces.shape[0]

    # Get vertices for each face
    v0 = vertices[faces[:, 0]]
    v1 = vertices[faces[:, 1]]
    v2 = vertices[faces[:, 2]]

    # Compute face normals vectorially
    normals = np.cross(v1 - v0, v2 - v0)
    norms = np.linalg.norm(normals, axis=1, keepdims=True)
    norms[norms == 0.0] = 1.0
    normals = normals / norms

    # Define a structured dtype for a single facet:
    # 3 floats (normal), 3 floats (v0), 3 floats (v1), 3 floats (v2), 1 uint16 (attribute byte count)
    # Total size per facet: 12 + 12 + 12 + 12 + 2 = 50 bytes.
    facet_dtype = np.dtype([
        ('normal', '<f4', (3,)),
        ('v0', '<f4', (3,)),
        ('v1', '<f4', (3,)),
        ('v2', '<f4', (3,)),
        ('attr', '<u2')
    ])

    facet_data = np.empty(F, dtype=facet_dtype)
    facet_data['normal'] = normals
    facet_data['v0'] = v0
    facet_data['v1'] = v1
    facet_data['v2'] = v2
    facet_data['attr'] = 0

    with open(filename, 'wb') as f:
        # 80-byte header
        header = b'Generated by globe3d.py'.ljust(80, b'\x00')
        f.write(header)
        # Write number of triangles
        f.write(struct.pack('<I', F))
        # Write all facets
        f.write(facet_data.tobytes())


def write_obj_with_vertex_colors(filename, vertices, faces, colors,
                                 center=(0.0, 0.0, 0.0), fix_normals=False):
    """Writes a mesh with per-vertex colors to an OBJ file.

    Vertex lines are written using the common vertex-color format: `v x y z r g b`.
    Uses vectorized NumPy formatting for high speed.

    Args:
        filename (str): Output OBJ file path.
        vertices (numpy.ndarray): Array of shape (n_points, 3) representing coordinates.
        faces (numpy.ndarray): Array of shape (n_faces, 3) representing face indices.
        colors (numpy.ndarray): Array of shape (n_points, 3) with RGB values in [0, 1].
        center (array-like, optional): Center of the sphere mesh. Only used if `fix_normals` is True.
            Defaults to (0.0, 0.0, 0.0).
        fix_normals (bool, optional): If True, applies `fix_face_chirality` to force face normals
            to point away from `center`. Defaults to False.
    """
    if fix_normals:
        faces_out = fix_face_chirality(vertices, faces, center)
    else:
        faces_out = faces

    with open(filename, 'w') as f:
        f.write("# OBJ file with vertex colors\n")
        # Horizontally stack vertices and colors: (V x 6)
        vc_data = np.column_stack([vertices, colors])
        np.savetxt(f, vc_data, fmt='v %.6f %.6f %.6f %.6f %.6f %.6f')
        # OBJ face indices are 1-based
        f_data = faces_out + 1
        np.savetxt(f, f_data, fmt='f %d %d %d')
